/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BlockManage: typeof import('./src/components/BlockManage.vue')['default']
    HomeBreadcrumbs: typeof import('./src/components/HomeBreadcrumbs.vue')['default']
    HomeToken: typeof import('./src/components/HomeToken.vue')['default']
    IHiArrowTopRightOnSquare16Solid: typeof import('~icons/heroicons/arrow-top-right-on-square16-solid')['default']
    IHiExternal: typeof import('~icons/heroicons/external')['default']
    IHiExternalLink: typeof import('~icons/heroicons/external-link')['default']
    IHiFaceFrown: typeof import('~icons/heroicons/face-frown')['default']
    IHiGlobeAlt: typeof import('~icons/heroicons/globe-alt')['default']
    IHiGlobeAlt16Solid: typeof import('~icons/heroicons/globe-alt16-solid')['default']
    IHiGlobeAlt20Solid: typeof import('~icons/heroicons/globe-alt20-solid')['default']
    IHiGlobeAltSolid: typeof import('~icons/heroicons/globe-alt-solid')['default']
    IHiGlobeAltSolid20: typeof import('~icons/heroicons/globe-alt-solid20')['default']
    IHiHeart: typeof import('~icons/heroicons/heart')['default']
    IHiHeartSolid: typeof import('~icons/heroicons/heart-solid')['default']
    IHiInformationCircle: typeof import('~icons/heroicons/information-circle')['default']
    IHiLockClosed: typeof import('~icons/heroicons/lock-closed')['default']
    IHiLockClosed20Solid: typeof import('~icons/heroicons/lock-closed20-solid')['default']
    IHiLockOpen: typeof import('~icons/heroicons/lock-open')['default']
    IHiLockOpen20Solid: typeof import('~icons/heroicons/lock-open20-solid')['default']
    IHiSquare2Stack: typeof import('~icons/heroicons/square2-stack')['default']
    IHiSquare2StackSolid: typeof import('~icons/heroicons/square2-stack-solid')['default']
    IHiXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    IIconExclamation: typeof import('~icons/icon/exclamation')['default']
    IIconGithub: typeof import('~icons/icon/github')['default']
    IIconHeart: typeof import('~icons/icon/heart')['default']
    IIconInfo: typeof import('~icons/icon/info')['default']
    IIconTelegram: typeof import('~icons/icon/telegram')['default']
    IIconX: typeof import('~icons/icon/x')['default']
    ImagePng: typeof import('./src/components/ImagePng.vue')['default']
    InscriptionList: typeof import('./src/components/InscriptionList.vue')['default']
    InscriptionListItem: typeof import('./src/components/InscriptionListItem.vue')['default']
    ModalActions: typeof import('./src/components/ModalActions.vue')['default']
    ModalActionsPng: typeof import('./src/components/ModalActionsPng.vue')['default']
    ModalCombine: typeof import('./src/components/ModalCombine.vue')['default']
    ModalGenerate: typeof import('./src/components/ModalGenerate.vue')['default']
    ModalSend: typeof import('./src/components/ModalSend.vue')['default']
    ModalTransactionApprove: typeof import('./src/components/ModalTransactionApprove.vue')['default']
    ModalTransactionConfirm: typeof import('./src/components/ModalTransactionConfirm.vue')['default']
    ModalTransactionPending: typeof import('./src/components/ModalTransactionPending.vue')['default']
    ModalTransactionSpending: typeof import('./src/components/ModalTransactionSpending.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheToasts: typeof import('./src/components/TheToasts.vue')['default']
  }
}
