/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    HomeBreadcrumbs: typeof import('./src/components/HomeBreadcrumbs.vue')['default']
    HomeToken: typeof import('./src/components/HomeToken.vue')['default']
    IHiArrowTopRightOnSquare16Solid: typeof import('~icons/heroicons/arrow-top-right-on-square16-solid')['default']
    IHiHeartSolid: typeof import('~icons/heroicons/heart-solid')['default']
    IHiInformationCircle: typeof import('~icons/heroicons/information-circle')['default']
    IHiXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    IIconGithub: typeof import('~icons/icon/github')['default']
    IIconX: typeof import('~icons/icon/x')['default']
    ImagePng: typeof import('./src/components/ImagePng.vue')['default']
    InscriptionList: typeof import('./src/components/InscriptionList.vue')['default']
    InscriptionListItem: typeof import('./src/components/InscriptionListItem.vue')['default']
    ModalActions: typeof import('./src/components/ModalActions.vue')['default']
    ModalCombine: typeof import('./src/components/ModalCombine.vue')['default']
    ModalGenerate: typeof import('./src/components/ModalGenerate.vue')['default']
    ModalSend: typeof import('./src/components/ModalSend.vue')['default']
    ModalTransactionConfirm: typeof import('./src/components/ModalTransactionConfirm.vue')['default']
    ModalTransactionPending: typeof import('./src/components/ModalTransactionPending.vue')['default']
    ModalTransactionSpending: typeof import('./src/components/ModalTransactionSpending.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheToasts: typeof import('./src/components/TheToasts.vue')['default']
  }
}
