/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BlockManage: typeof import('./src/components/BlockManage.vue')['default']
    IHiFaceFrown: typeof import('~icons/heroicons/face-frown')['default']
    IHiXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    IIconExclamation: typeof import('~icons/icon/exclamation')['default']
    IIconGithub: typeof import('~icons/icon/github')['default']
    IIconHeart: typeof import('~icons/icon/heart')['default']
    IIconInfo: typeof import('~icons/icon/info')['default']
    IIconX: typeof import('~icons/icon/x')['default']
    InscriptionList: typeof import('./src/components/InscriptionList.vue')['default']
    InscriptionListItem: typeof import('./src/components/InscriptionListItem.vue')['default']
    ModalCombine: typeof import('./src/components/ModalCombine.vue')['default']
    ModalGenerate: typeof import('./src/components/ModalGenerate.vue')['default']
    ModalSend: typeof import('./src/components/ModalSend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheToasts: typeof import('./src/components/TheToasts.vue')['default']
  }
}
